package app;

import DAO.interfaces.DAOProjetos;
import DAO.interfaces.DAOComponente;
import DAO.classes.DAOFactory;
import ifba.gestor_projetos.classes.Componente;
import ifba.gestor_projetos.classes.Projeto;
import javax.swing.DefaultComboBoxModel;
import ifba.gestor_projetos.enums.Tipos;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author gn10.lipe
 */
public class Novo_proj extends javax.swing.JFrame {
    DAOProjetos projetoDAO = DAOFactory.criarDAOProjetos();
    DAOComponente componenteDAO = DAOFactory.criarDAOComponente();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Novo_proj.class.getName());

    /**
     * Creates new form Reg_Comp
     */
    public Novo_proj() {
        initComponents();
    }
    
    private void carregar_combo() {
        DefaultComboBoxModel combo = new DefaultComboBoxModel(Tipos.values());
        this.seletorTipo.setModel(combo);
    }
    
    //LEMBRETE: AJUSTAR A LÓGICA DE INSERÇÃO DO PROJETO
    private void inserir(int proj) {
        Tipos selTipo = (Tipos) this.seletorTipo.getSelectedItem();
        Projeto projeto = new Projeto(this.gtTitulo.getText(), selTipo.toString(), LocalDate.now());
        Componente lider = new Componente((long)this.gtIDLattes.getValue() , this.gtNome.getText(), "lider", "ativo", LocalDate.now());        
        lider.setProjeto(proj);
        
        int[] linhas = {0 , 0}; 
        linhas[0] = projetoDAO.inserir(projeto);
        linhas[0] = componenteDAO.inserir(lider)[0];
        
        if (linhas[0] > 0 && linhas[1] > 0) {
            JOptionPane.showMessageDialog(this, "Projeto registrado com sucesso!");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao registrar o projeto.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnReg = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        gtTitulo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        gtIDLattes = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        gtNome = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        seletorTipo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(720, 405));
        setSize(new java.awt.Dimension(720, 405));
        setType(java.awt.Window.Type.POPUP);

        jLabel1.setFont(new java.awt.Font("Liberation Mono", 1, 18)); // NOI18N
        jLabel1.setText("Dados do projeto");

        jLabel2.setFont(new java.awt.Font("Liberation Mono", 1, 15)); // NOI18N
        jLabel2.setText("IDLattes:");

        jLabel3.setFont(new java.awt.Font("Liberation Mono", 1, 15)); // NOI18N
        jLabel3.setText("Titulo:");

        btnReg.setFont(new java.awt.Font("Liberation Mono", 1, 15)); // NOI18N
        btnReg.setText("Registrar");
        btnReg.addActionListener(this::btnRegActionPerformed);

        btnCancelar.setFont(new java.awt.Font("Liberation Mono", 1, 15)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        gtTitulo.setFont(new java.awt.Font("Liberation Mono", 0, 15)); // NOI18N
        gtTitulo.addActionListener(this::gtTituloActionPerformed);

        jLabel5.setFont(new java.awt.Font("Liberation Mono", 0, 13)); // NOI18N
        jLabel5.setText("Sistema Integrado de Gestão de Projetos");

        try {
            gtIDLattes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("################")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        gtIDLattes.addActionListener(this::gtIDLattesActionPerformed);

        jLabel6.setFont(new java.awt.Font("Liberation Mono", 1, 15)); // NOI18N
        jLabel6.setText("Nome:");

        gtNome.setFont(new java.awt.Font("Liberation Mono", 0, 15)); // NOI18N
        gtNome.addActionListener(this::gtNomeActionPerformed);

        jLabel7.setFont(new java.awt.Font("Liberation Mono", 1, 24)); // NOI18N
        jLabel7.setText("Adicionar Projeto");

        jLabel8.setFont(new java.awt.Font("Liberation Mono", 1, 15)); // NOI18N
        jLabel8.setText("Tipo:");

        seletorTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setFont(new java.awt.Font("Liberation Mono", 1, 18)); // NOI18N
        jLabel9.setText("Dados do Líder");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                        .addComponent(btnReg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar)
                        .addGap(11, 11, 11))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(gtIDLattes, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                                .addComponent(jLabel9)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel8))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(gtTitulo)
                                        .addComponent(seletorTipo, 0, 255, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(42, 42, 42)
                                    .addComponent(gtNome))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(228, 228, 228)
                    .addComponent(jLabel7)
                    .addContainerGap(254, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(gtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(seletorTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(gtIDLattes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(gtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnReg)
                        .addComponent(btnCancelar))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(jLabel7)
                    .addContainerGap(363, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void gtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gtTituloActionPerformed

    private void gtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gtNomeActionPerformed

    private void gtIDLattesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gtIDLattesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gtIDLattesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnReg;
    private javax.swing.JFormattedTextField gtIDLattes;
    private javax.swing.JTextField gtNome;
    private javax.swing.JTextField gtTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> seletorTipo;
    // End of variables declaration//GEN-END:variables
}
