/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

/**
 *
 * @author gn10.lipe
 */
public class Projeto_Pag extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Projeto_Pag.class.getName());

    /**
     * Creates new form Projeto_Pag
     */
    public Projeto_Pag() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAddComp = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        codProjLb = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tpProjLb = new javax.swing.JLabel();
        dtIniProjLb = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        estProjLb = new javax.swing.JLabel();
        dtFmProjLb = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbComponentes = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        btnDslComp = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbComponentes1 = new javax.swing.JTable();
        btnAddAvs = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnspndComp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1080, 720));
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1080, 720));

        jLabel1.setFont(new java.awt.Font("Liberation Mono", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nome do Projeto");

        btnAddComp.setFont(new java.awt.Font("Liberation Mono", 1, 15)); // NOI18N
        btnAddComp.setText("Registrar");

        btnVoltar.setFont(new java.awt.Font("Liberation Mono", 1, 15)); // NOI18N
        btnVoltar.setText("Voltar");

        jLabel2.setFont(new java.awt.Font("Liberation Mono", 1, 18)); // NOI18N
        jLabel2.setText("Código do Projeto: ");

        codProjLb.setFont(new java.awt.Font("Liberation Mono", 1, 18)); // NOI18N
        codProjLb.setText("codigo do Projeto ");

        jLabel3.setFont(new java.awt.Font("Liberation Mono", 1, 18)); // NOI18N
        jLabel3.setText("Tipo do Projeto: ");

        tpProjLb.setFont(new java.awt.Font("Liberation Mono", 1, 18)); // NOI18N
        tpProjLb.setText("tipo do Projeto ");

        dtIniProjLb.setFont(new java.awt.Font("Liberation Mono", 1, 18)); // NOI18N
        dtIniProjLb.setText("inicio do Projeto ");

        jLabel4.setFont(new java.awt.Font("Liberation Mono", 1, 18)); // NOI18N
        jLabel4.setText("Início do Projeto: ");

        jLabel5.setFont(new java.awt.Font("Liberation Mono", 1, 18)); // NOI18N
        jLabel5.setText("Estado do Projeto: ");

        estProjLb.setFont(new java.awt.Font("Liberation Mono", 1, 18)); // NOI18N
        estProjLb.setText("estado do Projeto ");

        dtFmProjLb.setFont(new java.awt.Font("Liberation Mono", 1, 18)); // NOI18N
        dtFmProjLb.setText("fim do Projeto ");

        jLabel6.setFont(new java.awt.Font("Liberation Mono", 1, 18)); // NOI18N
        jLabel6.setText("Fim do Projeto: ");

        tbComponentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "LattesId", "Nome", "Função", "Estado", "Entrada", "Saída"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbComponentes);

        jLabel7.setFont(new java.awt.Font("Liberation Mono", 1, 18)); // NOI18N
        jLabel7.setText("Componentes");

        btnDslComp.setFont(new java.awt.Font("Liberation Mono", 1, 15)); // NOI18N
        btnDslComp.setText("Desligar");

        tbComponentes1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Remetente", "Aviso", "Publicação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbComponentes1);

        btnAddAvs.setFont(new java.awt.Font("Liberation Mono", 1, 15)); // NOI18N
        btnAddAvs.setText("Novo Aviso");

        jLabel8.setFont(new java.awt.Font("Liberation Mono", 1, 18)); // NOI18N
        jLabel8.setText("Avisos");

        btnspndComp.setFont(new java.awt.Font("Liberation Mono", 1, 15)); // NOI18N
        btnspndComp.setText("Suspender");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)
                        .addGap(16, 16, 16)
                        .addComponent(codProjLb))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tpProjLb)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(dtIniProjLb))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(estProjLb))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel6)
                        .addGap(51, 51, 51)
                        .addComponent(dtFmProjLb))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel7)
                        .addGap(463, 463, 463)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddComp)
                                .addGap(6, 6, 6)
                                .addComponent(btnspndComp)
                                .addGap(6, 6, 6)
                                .addComponent(btnDslComp)
                                .addGap(231, 231, 231)
                                .addComponent(btnAddAvs)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnVoltar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(codProjLb))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tpProjLb)
                        .addGap(6, 6, 6)
                        .addComponent(dtIniProjLb)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(estProjLb))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(dtFmProjLb))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddComp)
                    .addComponent(btnspndComp)
                    .addComponent(btnDslComp)
                    .addComponent(btnAddAvs))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVoltar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAvs;
    private javax.swing.JButton btnAddComp;
    private javax.swing.JButton btnDslComp;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JButton btnspndComp;
    private javax.swing.JLabel codProjLb;
    private javax.swing.JLabel dtFmProjLb;
    private javax.swing.JLabel dtIniProjLb;
    private javax.swing.JLabel estProjLb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbComponentes;
    private javax.swing.JTable tbComponentes1;
    private javax.swing.JLabel tpProjLb;
    // End of variables declaration//GEN-END:variables
}
